### ISSUE TITLE
fermion/boson

### ISSUE THREAD

**Issue by shinaoka** [SpM-lab/SparseIR.jl#38]
The symbols `boson` and `fermion` are now gone. Can we reintroduce them?

**Comment by mwallerb** [comment]
We removed them, because they were simply duplicates of `Fermionic()` and `Bosonic()`.

Do you need these constants specifically?

**Comment by shinaoka** [comment]
I found that most of our code including the tutorials does not run anymore. That's a bit annoying.

**Comment by mwallerb** [comment]
I'd rather not reintroduce them, because we export quite a lot of symbols from SparseIR already as it is. Also, I don't think the names `fermion`/`boson` are particularly well-chosen constants, `Fermionic()` and `Bosonic()` are IMHO better in that respect ...

But of course breaking code is not good ... If you like, I can make a quick search/replace in the tutorials ...

**Comment by shinaoka** [comment]
I have updated the docker image:
https://hub.docker.com/r/shinaoka/sparse-ir
This should be automated somehow...

I'd appreciate it if you update the tutorials kindly.

**Comment by mwallerb** [comment]
Done.
https://github.com/SpM-lab/sparse-ir-tutorial/commit/051edfe8c87b631da2ae724440f302fbbb87cbf0
